### ISSUE TITLE
How did you get into speaking?

### ISSUE THREAD

**Issue by sindresorhus** [nzakas/ama#12]
Any tips for beginners wanting to try it?

**Comment by nzakas** [comment]
From my post, [The thank you that changed my life](http://www.nczonline.net/blog/2012/10/30/the-thank-you-that-changed-my-life/):

> I met Bill Scott through my cubemate, Adam Platti. I had mentioned to Adam that I wanted to start giving talks and I didn’t know how to go about it. Adam said that his friend Bill did talks all the time and I should chat with him to figure out how to do it. He then made an introduction to Bill, and Bill made an introduction to the organizer of the Rich Web Experience, which was taking place in San Jose. That was my first conference speaking opportunity. The experience made me realize that not only could I give a talk, but people actually liked it. From then on, I was giving talks at conferences and other events.

Bill really started it all for me. The drive to start giving talks was probably more ego at that point than anything else, but I knew I wanted to try it.

I did do a [post](http://www.nczonline.net/blog/2013/01/10/advice-for-new-and-aspiring-technical-speakers/) on tips for beginners as well, but it really comes down to just start doing talks. Start small, with a 10-20 minute talk at a small meetup or with your team at work. Pick a topic that interests you and tell a story about it. Realize that very few speakers are experts, and the only thing separating you from them is their willingness to get up in front of people and speak.
