### ISSUE TITLE
What do you think about Typescript? Which one do you think will get widespread support..Babel or Typescript?

### ISSUE THREAD

**Issue by ammark** [nzakas/ama#18]

**Comment by nzakas** [comment]
I like the idea of TypeScript. Development-time type annotations and type checking that are removed for deployment makes a lot of sense. I don't agree with all the design decisions, but I think the foundation and overall approach is really good.

Going forward, I see Babel as a general purpose tool for building things like TypeScript, so I dint think it's a mutually exclusive decision. I do think optional type checking will make it into JavaScript someday.
