### ISSUE TITLE
What does your dev environment look like?

### ISSUE THREAD

**Issue by sindresorhus** [nzakas/ama#2]
Editor, terminal, tools, themes, fonts, process, etc.

**Comment by nzakas** [comment]
My setup is pretty Spartan:
1. Windows 7
2. Git bash for terminal
3. Sublime Text with default theme

I don't have a ton of personal automation aside from two scripts: `ws` and `wd` (work start and work done). So `ws123` creates a new branch called `issue123` fetches origin, and sets it to origin/master for a clean start. `wd123` deletes `issue123` both locally and remotely.
