### ISSUE TITLE
What's feature of JS you've felt is the most misunderstood feature of JS for newcomers & what you think can be done for it to be less misunderstood in the future? 

### ISSUE THREAD

**Issue by lozandier** [nzakas/ama#24]

**Comment by nzakas** [comment]
I think prototypes are easily the most misunderstood. I don't think they are necessarily complicated, I just think people don't take the time to really understand them.

As a developer, I think the best way to learn is to stop thinking about using classes as you would in Java or C++ , just completely remove that way of thinking .

**Comment by Ben52** [comment]
What do you think about ES6 adding the class construct?

**Comment by nzakas** [comment]
See http://www.nczonline.net/blog/2012/10/16/does-javascript-need-classes/
