### ISSUE TITLE
What you think are overrated ways of evaluating whether a JS developer is a work-ready developer, and what ways should be perhaps considered instead?

### ISSUE THREAD

**Issue by lozandier** [nzakas/ama#25]

**Comment by nzakas** [comment]
Trivia contests are overrated. What I mean is asking questions like, "what is a closure?" Giving people tests like this only allows you to hire the best communicators, and those aren't necessarily the best developers. Additionally, some people develop communication skills late or never.

It's much better to give a problem and let them with through a solution with actual code. Then ask them to explain what they did. They might not be able to explain all the minute details, but you should get a good sense of what they know
