### ISSUE TITLE
What advice would you give to a young college graduate for a great career in web development.

### ISSUE THREAD

**Issue by chirgjn** [nzakas/ama#28]
Hi,
First of all a very happy birthday. I am a big fan of yours, from your talks.

I am a fresh CS graduate, really enthusiastic about web development.
I know basics of Ruby, Python, Bash scripting and C.
I have also tried my hand at OO-PHP.
I am a fairly familiar with jQuery, Bootstrap.

And last but not the least I am really passionate about JavaScript, I have knowledge of closures and prototypal inheritance and object composition.

But still struggling to find a job. What should be my next step.

**Comment by nzakas** [comment]
Keep learning, keep practicing, keep reading. Build things for yourself, try to duplicate applications you're familiar with.

Most of all, be willing to listen. Job markets are different in different parts of the world, so I can't tell you exactly what to do. All I can tell you is it took me seven years before I had the first job that felt perfect to me. Commit yourself to working hard and learning, and eventually sometime will notice.
