### ISSUE TITLE
I'm starting with JavaScript. How to continue develop skills?

### ISSUE THREAD

**Issue by pawelgrzybek** [nzakas/ama#31]
I learn JavaScript. I really getting into it but few concepts are still very confusing for me. I'm overwhelmed by new fancy tools that people use (jquery, react, angular, node). Can you give me any suggestions how could I go trhroug JvaScript learning path without loosing mind.

**Comment by nzakas** [comment]
Just keep coding. Give yourself projects. Try to create things you see in libraries and web applications that you use.

There's no shortcut, you just have to keep practicing.
