### ISSUE TITLE
How do you feel about Yahoo! now?

### ISSUE THREAD

**Issue by hemanth** [nzakas/ama#32]
If I'm not wrong you were on the exceptional performance team at Yahoo! And would have done wonderful things there.

**Comment by nzakas** [comment]
I wasn't on the exceptional performance team. I was in the My Yahoo team, the front-page team, and the media foundation team.

I think Yahoo is a company still searching for a purpose. Still a lot of really smart engineers, but the company as a whole doesn't inspire me.

**Comment by hemanth** [comment]
:+1:
