### ISSUE TITLE
Your thoughts on freelancing? Have you ever worked as one, and would you consider that in the future?

### ISSUE THREAD

**Issue by fuzinato** [nzakas/ama#33]

**Comment by nzakas** [comment]
I've never worked as a freelancer. I define freelancer as "coding for hire," which I have no interest in doing. I prefer more strategic work. I have been a consultant in the past, providing strategic services to clients, but not delivering any code.

I think freelancer is a really great option for those who like to be working on a bunch of different things and don't mind the overhead of finding and managing clients. It's just not for me.
