### ISSUE TITLE
Why people stress to use Immutable structures in javascript ?

### ISSUE THREAD

**Issue by asvny** [nzakas/ama#34]

**Comment by nzakas** [comment]
Immutable structures allow the consumers of those structures to behave in expected ways. For instance, if you passed an object to a function and then function kept a reference to the object around, the function would have no idea if any of the properties changed. When you guarantee the object is immutable, the function no longer has to worry that the properties have changed and therefore the last call might need to be updated.

**Comment by asvny** [comment]
Thanks !
