### ISSUE TITLE
Hey, 'for in' loop seems faster than 'for' in javascript ?  [ I have attached the perf screenshot ]

### ISSUE THREAD

**Issue by asvny** [nzakas/ama#36]
![screen shot 2015-08-08 at 11 25 21 am](https://cloud.githubusercontent.com/assets/5235065/9149290/ff62f338-3dc0-11e5-889a-0c112a849219.png)

I repeated about 4 to 5 times ...always 'for in' seems faster ..why ?

while(length--) is faster .....but just want to know among these two :wink: :wink:

**Comment by nzakas** [comment]
I don't know. Micro benchmarks are generally useless: http://mrale.ph/blog/2012/12/15/microbenchmarks-fairy-tale.html

**Comment by asvny** [comment]
Ohh.. I get that
