### ISSUE TITLE
I have read your book and one of the section is that it is better to use local variable to store the value of array element or object in case if it is used more than one time. I tried to do some tests and results shown no difference. What is your opion nowadays? Thanks.

### ISSUE THREAD

**Issue by sszenchenko** [nzakas/ama#42]

**Comment by nzakas** [comment]
I'm assuming you mean High Performance JavaScript? (I've written many books.)

That book is quite old, so it's definitely not up to date with the latest. As always, you should do some profiling and figure out if it makes a difference for you.
