### ISSUE TITLE
Question about buying your book - High Performance JavaScript

### ISSUE THREAD

**Issue by konekoya** [nzakas/ama#45]
Thinking about buying this book, but I heard(from Kyle Simpson's workshop video) that you're working on second edition of this book. So my question is: should I wait for the second edition or just go ahead and buy the first edition? One of the concerns of buying the first edition is that it was published so many years ago, I'm not sure if the content is still relevant today.

Thank you!

**Comment by nzakas** [comment]
I'm not working on a second edition. I don't know if anyone else is. I'd say at least half of the book is still relevant, and the other half isn't bad advice, it just doesn't give you a huge boost anymore.
