### ISSUE TITLE
What was your weirdest moment?

### ISSUE THREAD

**Issue by sholladay** [nzakas/ama#48]
On your blog, you have mentioned receiving [applied kinesiology](https://en.wikipedia.org/wiki/Applied_kinesiology), amongst other things. And you described it as a pretty far out experience, saying:

> when you’re fed up with doctors telling you you’re not sick, you will do anything and see anyone who might give you a glimmer of hope

So certainly life can be a wild ride. What moment in your life do you consider the weirdest of all?

**Comment by nzakas** [comment]
The moment when someone asked me what my weirdest moment was. :)
