### ISSUE TITLE
what keyboard/mouse do you use at work?

### ISSUE THREAD

**Issue by xerosanyam** [nzakas/ama#51]

**Comment by nzakas** [comment]
![D464C8BA-C527-44FB-938A-F774D8CF3B1D](https://user-images.githubusercontent.com/38546/86837762-3956d800-c054-11ea-9cc7-88fa5ea91e51.jpeg)

**Comment by nzakas** [comment]
That's the Goldtouch SK-2730 and a Kensington trackball
