### ISSUE TITLE
How do you think we could do open source better?

### ISSUE THREAD

**Issue by sindresorhus** [nzakas/ama#7]

**Comment by nzakas** [comment]
I think open source is really lacking a set of best practices and tools to enforce or encourage them. Everyone is doing it from scratch. I'd like to see standards emerge around things like codes of conduct (make it similar to licenses - just pick one and don't rewrite for each project), CLAs, pull request validation, appropriate patch landing processes, frequency of releases, etc. 

We need to start having these conversations so every project doesn't need to reinvent the wheel.

**Comment by sindresorhus** [comment]
Seems like the start of a good blog post to inspire people to do this. Hint hint ;)
