### ISSUE TITLE
What's the best book you've ever read?

### ISSUE THREAD

**Issue by sindresorhus** [nzakas/ama#9]

**Comment by nzakas** [comment]
Ah, tough as I've read a lot of good stuff. If I had to pick one that had the biggest impact on me it would be [Anger](http://www.amazon.com/Anger-Cooling-Thich-Nhat-Hanh/dp/1573229377/ref=sr_1_1?ie=UTF8&qid=1436718933&sr=8-1&keywords=Anger) by Thich Nhat Hanh. That book found its way into my life at exactly the right time and I still recommend it people.
